// Локальная копия меню — используется в системном промпте голосового бариста.
// Обновить вручную при изменении меню в Baserow.

import type { MenuItem } from "@/lib/menuData";

export const localMenu: MenuItem[] = [
  { id: 4,  name: "Капучино",        category: { value: "Coffee" },    popular: true,  variants: [{ sizeName: "маленький", ml: 250, price: "180" }, { sizeName: "средний", ml: 300, price: "230" }, { sizeName: "большой", ml: 400, price: "280" }] },
  { id: 5,  name: "Латте",           category: { value: "Coffee" },    popular: false, variants: [{ sizeName: "средний", ml: 300, price: "230" }, { sizeName: "большой", ml: 400, price: "280" }] },
  { id: 34, name: "Эспрессо",        category: { value: "Coffee" },    popular: true,  variants: [{ sizeName: "одинарный", ml: 25, price: "120" }, { sizeName: "двойной", ml: 50, price: "140" }] },
  { id: 67, name: "Американо",       category: { value: "Coffee" },    popular: false, variants: [{ sizeName: null, ml: null, price: "150" }] },
  { id: 68, name: "Айс с урбечом",   category: { value: "Coffee" },    popular: true,  variants: [{ sizeName: "большой", ml: 400, price: "350" }] },
  { id: 69, name: "Айс Латте",       category: { value: "Coffee" },    popular: true,  variants: [{ sizeName: "средний", ml: 300, price: "230" }] },
  { id: 70, name: "Бамбл кофе",      category: { value: "Coffee" },    popular: true,  variants: [{ sizeName: "средний", ml: 300, price: "400" }] },
  { id: 71, name: "Фраппе",          category: { value: "Coffee" },    popular: false, variants: [{ sizeName: "средний", ml: 300, price: "250" }] },
  { id: 72, name: "Раф",             category: { value: "Coffee" },    popular: true,  variants: [{ sizeName: "маленький", ml: 250, price: "200" }, { sizeName: "средний", ml: 300, price: "250" }, { sizeName: "большой", ml: 400, price: "350" }] },
  { id: 73, name: "Горячий шоколад", category: { value: "Chocolate" }, popular: false, variants: [{ sizeName: "маленький", ml: 250, price: "200" }, { sizeName: "средний", ml: 300, price: "250" }, { sizeName: "большой", ml: 400, price: "300" }] },
  { id: 74, name: "Айва с персиком", category: { value: "Tea" },       popular: false, variants: [{ sizeName: "чайник", ml: 500, price: "200" }] },
  { id: 75, name: "Граф Орлов",      category: { value: "Tea" },       popular: false, variants: [{ sizeName: "чайник", ml: 500, price: "200" }] },
  { id: 76, name: "Дикая вишня",     category: { value: "Tea" },       popular: false, variants: [{ sizeName: "чайник", ml: 500, price: "200" }] },
  { id: 77, name: "Имбирный",        category: { value: "Tea" },       popular: false, variants: [{ sizeName: "чайник", ml: 500, price: "200" }] },
  { id: 78, name: "Лев",             category: { value: "Tea" },       popular: false, variants: [{ sizeName: "чайник", ml: 500, price: "200" }] },
  { id: 79, name: "Банановый",       category: { value: "Milkshake" }, popular: false, variants: [{ sizeName: "большой", ml: 400, price: "300" }] },
  { id: 80, name: "Клубничный",      category: { value: "Milkshake" }, popular: false, variants: [{ sizeName: "большой", ml: 400, price: "300" }] },
  { id: 81, name: "Молочный",        category: { value: "Milkshake" }, popular: false, variants: [{ sizeName: "большой", ml: 400, price: "300" }] },
  { id: 82, name: "Шоколадный",      category: { value: "Milkshake" }, popular: false, variants: [{ sizeName: "большой", ml: 400, price: "300" }] },
  { id: 83, name: "Апельсиновый",    category: { value: "Fresh" },     popular: true,  variants: [{ sizeName: "средний", ml: 300, price: "300" }] },
  { id: 84, name: "Яблочный",        category: { value: "Fresh" },     popular: false, variants: [{ sizeName: "средний", ml: 300, price: "300" }] },
  { id: 85, name: "Яблоко-Апельсин", category: { value: "Fresh" },     popular: false, variants: [{ sizeName: "средний", ml: 300, price: "300" }] },
  { id: 86, name: "Гранат-Апельсин", category: { value: "Fresh" },     popular: false, variants: [{ sizeName: "средний", ml: 300, price: "300" }] },
  { id: 87, name: "Ананасовый",      category: { value: "Lemonade" },  popular: false, variants: [{ sizeName: "большой", ml: 400, price: "200" }] },
  { id: 88, name: "Голубая лагуна",  category: { value: "Lemonade" },  popular: false, variants: [{ sizeName: "большой", ml: 400, price: "200" }] },
  { id: 89, name: "Манго-маракуя",   category: { value: "Lemonade" },  popular: false, variants: [{ sizeName: "большой", ml: 400, price: "200" }] },
  { id: 90, name: "Мохито классический", category: { value: "Lemonade" }, popular: false, variants: [{ sizeName: "большой", ml: 400, price: "200" }] },
  { id: 91, name: "Мохито клубничный",   category: { value: "Lemonade" }, popular: false, variants: [{ sizeName: "большой", ml: 400, price: "200" }] },
  { id: 92, name: "Мохито манго",        category: { value: "Lemonade" }, popular: false, variants: [{ sizeName: "большой", ml: 400, price: "200" }] },
  { id: 93, name: "Мохито ягодный",      category: { value: "Lemonade" }, popular: false, variants: [{ sizeName: "большой", ml: 400, price: "200" }] },
  { id: 94, name: "Тоска индейца",       category: { value: "Lemonade" }, popular: true,  variants: [{ sizeName: "большой", ml: 400, price: "250" }] },
  { id: 95, name: "Яблочный",            category: { value: "Lemonade" }, popular: false, variants: [{ sizeName: "большой", ml: 400, price: "200" }] },
  { id: 96, name: "Тоник",              category: { value: "Lemonade" }, popular: true,  variants: [{ sizeName: "средний", ml: 300, price: "250" }, { sizeName: "большой", ml: 400, price: "300" }] },
  { id: 97, name: "Круассан",           category: { value: "Dessert" },  popular: true,  variants: [{ sizeName: "средний", ml: 300, price: "150" }] },
];
